# Generated by Django 5.0.7 on 2024-07-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_fooditem_submittedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='submitted_by',
        ),
    ]
