# Generated by Django 5.0.7 on 2024-07-15 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipedetail_delete_user_fooditem_submitted_by_and_more'),
    ]

    operations = [
    ]
