# Generated by Django 5.0.7 on 2024-07-15 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20240715_1705'),
        ('recipes', '0009_auto_20240715_1724'),
    ]

    operations = [
    ]
