# Generated by Django 5.0.7 on 2024-07-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20240715_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipedetail',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
