# Generated by Django 5.0.7 on 2024-07-15 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipedetail_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipedetail',
            name='recipe_image',
        ),
    ]
